[package]
name = "rustfish-bot"
version = "0.1.0"
edition = "2021"
description = "Rust Chess Engine"
license = "Apache 2.0"
homepage = "https://https://github.com/boweihan/rustfish"
repository = "https://https://github.com/boweihan/rustfish"
readme = "../README.md"

[dependencies]